---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  product_name: chef
  product_version: latest
  channel: stable
  install_strategy: once
  always_update_cookbooks: true
  #log_level: info

verifier:
  name: inspec

platforms:
  - name: centos-7

suites:
  - name: default
    driver:
      vm_hostname: python
      customize:
        memory: 1024
        cpuexecutioncap: 25
        natdnshostresolver1: "on"
      network:
    run_list:
      - recipe[yum-epel]
      - recipe[python-chef::python2]
      - recipe[python-chef::python3]
      - recipe[python-chef::virtualenv]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
      dev_mode: true
      python:
        virtualenvs:
          python2:
            python: '/bin/python2'
            dest_dir: '/opt/virtualenv/python2'
            pips: []
          python3:
            python: '/bin/python3.6'
            dest_dir: '/opt/virtualenv/python3'
            pips: []
