name 'python-chef'
maintainer 'Ryan Hansohn'
maintainer_email 'info@imnorobot.com'
license 'MIT'
description 'Installs/Configures python-chef'
version '0.2.1'
chef_version '>= 13.0'
source_url 'https://github.com/hansohn/python-chef'
issues_url 'https://github.com/hansohn/python-chef/issues'

supports 'centos', '>= 7.0'
